---

# Install OpenVPN

- name: Download file
  get_url:
    url: https://raw.githubusercontent.com/Nyr/openvpn-install/master/openvpn-install.sh
    dest: /tmp/openvpn-install.sh

- name: Copy configuration file
  template:
    src: files/openvpn-configure.sh
    dest: /usr/local/bin/openvpn-configure.sh
    owner: root
    group: root
    mode: 0755

- name: Run configuration
  command: openvpn-configure.sh
